name: CI

on:
  release:
    # We'll run this workflow when a new GitHub release is created
    types: [released]

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare environment
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Build all artifacts
        id: buildAll
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleDebug
      - name: Run Kotlin Format Source
        run: ./gradlew ktlintFormat
      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Notify on Slack
        uses: act10ns/slack@v1.0.9
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
